# Generated by Django 6.0.6 on 2026-08-04 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='标识')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_count', models.PositiveIntegerField(default=0, verbose_name='文档数')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='向量数')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file', models.FileField(upload_to='documents/', verbose_name='文件')),
                ('file_type', models.CharField(default='pdf', max_length=10, verbose_name='类型')),
                ('md_content', models.TextField(blank=True, default='', verbose_name='OCR/提取的 Markdown')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('ocr', 'OCR 中'), ('indexing', '向量化中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='向量数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kb.knowledgebase')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'ordering': ['-created_at'],
            },
        ),
    ]
