# Generated by Django 6.0.6 on 2026-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stage_detail',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='阶段详情'),
        ),
    ]
