# Generated by Django 6.0.6 on 2026-08-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_document_stage_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_base_url', models.CharField(blank=True, default='', max_length=255, verbose_name='LLM Base URL')),
                ('llm_api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='LLM API Key')),
                ('llm_model', models.CharField(blank=True, default='', max_length=120, verbose_name='LLM 模型')),
                ('llm_temperature', models.FloatField(blank=True, null=True, verbose_name='LLM 温度')),
                ('embedding_base_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Embedding Base URL')),
                ('embedding_api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Embedding API Key')),
                ('embedding_model', models.CharField(blank=True, default='', max_length=120, verbose_name='Embedding 模型')),
                ('embedding_dimensions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Embedding 维度')),
                ('kb_chunk_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='分块大小')),
                ('kb_chunk_overlap', models.PositiveIntegerField(blank=True, null=True, verbose_name='分块重叠')),
                ('kb_top_k', models.PositiveIntegerField(blank=True, null=True, verbose_name='Top K')),
                ('mineru_api_base', models.CharField(blank=True, default='', max_length=255, verbose_name='MinerU API Base')),
                ('mineru_api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='MinerU API Key')),
                ('mineru_backend', models.CharField(blank=True, default='', max_length=60, verbose_name='MinerU Backend')),
                ('mineru_lang', models.CharField(blank=True, default='', max_length=30, verbose_name='MinerU 语言')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
