# Generated by Django 6.0.6 on 2026-08-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('data', models.JSONField(default=dict, verbose_name='配置快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '配置预设',
                'verbose_name_plural': '配置预设',
                'ordering': ['name'],
            },
        ),
    ]
