# Generated by Django 6.0.6 on 2026-08-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0005_configpreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configpreset',
            options={'ordering': ['category', 'name'], 'verbose_name': '配置预设', 'verbose_name_plural': '配置预设'},
        ),
        migrations.AddField(
            model_name='configpreset',
            name='category',
            field=models.CharField(choices=[('llm', 'LLM'), ('embedding', '向量模型'), ('retrieval', '检索参数'), ('mineru', 'MinerU OCR')], default='llm', max_length=20, verbose_name='分类'),
        ),
    ]
