# Generated by Django 6.0.6 on 2026-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_alter_configpreset_options_configpreset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='html_built_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='HTML 构建时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='html_content',
            field=models.TextField(blank=True, default='', verbose_name='HTML 正文'),
        ),
        migrations.AddField(
            model_name='message',
            name='citations',
            field=models.JSONField(blank=True, default=list, verbose_name='来源出处'),
        ),
    ]
