# Generated by Django 6.0.6 on 2026-08-09 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_document_html_built_at_document_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='is_folder',
            field=models.BooleanField(default=False, verbose_name='是否文件夹'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kb.knowledgebase', verbose_name='父知识库'),
        ),
    ]
