# Generated by Django 6.0.6 on 2026-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0023_message_completion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='未完成原因'),
        ),
    ]
