# Generated by Django 6.0.6 on 2026-09-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0024_message_failure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='completion_status',
            field=models.CharField(choices=[('complete', '完整'), ('incomplete', '未完成'), ('queued', '排队中'), ('running', '生成中')], default='complete', max_length=12, verbose_name='回答状态'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('completion_status__in', ['queued', 'running'])), fields=('conversation',), name='one_active_answer_per_conversation'),
        ),
    ]
