# Generated by Django 6.0.6 on 2026-09-19 22:39

from django.db import migrations, models


def mark_existing_read(apps, schema_editor):
    from django.db.models import Max
    Message = apps.get_model('kb', 'Message')
    Conversation = apps.get_model('kb', 'Conversation')
    alias = schema_editor.connection.alias
    for row in Message.objects.using(alias).filter(role='ai', completion_status='complete').values('conversation_id').annotate(latest=Max('pk')).iterator():
        Conversation.objects.using(alias).filter(pk=row['conversation_id']).update(last_read_answer_id=row['latest'])


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0025_background_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_read_answer_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RunPython(mark_existing_read, migrations.RunPython.noop),
    ]
